server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git: 
          uri: git@github.com:liuhaoyu519/microservicecloud-config.git #GitHub上面的git仓库名字
          strict-host-key-checking: false
#          username: liuhaoyu519
#          password: l,h,y.123.
